spring:
  profiles:
    active: dev
##zhouhuasheng: 2a2ad0d12d9bfdd1f5ce20e91e8444dd1379b713
server:
  ssl:
    key-store: classpath:3097886_www.zhouhuasheng.top.pfx
    key-store-password: sLczBIj8
    key-store-type: PKCS12
  port: 8080
