spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.97.182.0:3306/hello?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: c849750b1e00cc10

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        strategy:  org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false
  redis:
    host: 127.0.0.1
    port: 6379

upload:
    dir: D://meet//
    host: localhost:8002/
    url: image/






oss:
  endpoint: oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAI4Fe99vP6pef9XvzQXCUM
  bucketName: z-study-resource
  accessKeySecret: V9c2IamvkeGrqNODwOfKbIh5EXzzyv









info:
  head: head
  body: body
management:
  endpoints:
    web:
      exposure:
        #加载所有的端点，默认只加载了info、health
        include: '*'
  endpoint:
    health:
      show-details: always
    #可以关闭指定的端点
    shutdown:
      enabled: false

